# Generated by Django 5.2.4 on 2025-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos/')),
            ],
        ),
    ]
